# Generated by Django 3.2 on 2023-03-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=26, verbose_name='Наименование')),
                ('leads', models.IntegerField(verbose_name='Количество выводов')),
                ('aliases', models.CharField(blank=True, max_length=40, verbose_name='Псевдонимы')),
                ('image', models.ImageField(blank=True, upload_to='img/packages/small')),
                ('image_small_width', models.IntegerField(blank=True)),
                ('image_small_height', models.IntegerField(blank=True)),
                ('image_big', models.ImageField(blank=True, upload_to='img/packages/big')),
                ('image_big_width', models.IntegerField(blank=True)),
                ('image_big_height', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['title'],
            },
        ),
    ]
